name: bls_internal
description: A new Flutter package project.
version: 0.0.1
homepage: https://beyondlabs.studio

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  dartx: ^1.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
